DROP TABLE IF EXISTS phone_numbers, consumers, consumers_phone_numbers, device_types, devices;
CREATE TABLE IF NOT EXISTS phone_numbers
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    number VARCHAR(11) NOT NULL,
    CONSTRAINT uq_user_email UNIQUE (number),
    CONSTRAINT pk_user PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS consumers
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sure_name VARCHAR(255) NOT NULL,
    name      VARCHAR(255),
    last_name VARCHAR(255),
    comments  VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS consumers_phone_numbers
(
    consumer_id BIGINT NOT NULL,
    number_id   BIGINT NOT NULL,
    CONSTRAINT pk_cons_phone_num PRIMARY KEY (consumer_id, number_id),
    CONSTRAINT fk_consumer_id FOREIGN KEY (consumer_id) REFERENCES consumers (id) ON DELETE CASCADE,
    CONSTRAINT fk_number_id FOREIGN KEY (number_id) REFERENCES phone_numbers (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS device_types
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(255) NOT NULL,
    CONSTRAINT uq_type UNIQUE (type)
);

CREATE TABLE IF NOT EXISTS devices
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_id   BIGINT NOT NULL,
    brand     VARCHAR(255),
    model     VARCHAR(255),
    alternate VARCHAR(255),
    CONSTRAINT uq_model UNIQUE (model),
    CONSTRAINT fk_type_id FOREIGN KEY (type_id) REFERENCES device_types (id) ON DELETE CASCADE
);